<a href="https://colab.research.google.com/github/nishu-mns/ML-Labs/blob/main/ML_lab_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
x=5
print(x,"TYPE: ",type(x))
x="Hello"
print(x,"TYPE: ",type(x))
x=[1,2,3]
print(x,"TYPE: ",type(x))

5 TYPE:  <class 'int'>
Hello TYPE:  <class 'str'>
[1, 2, 3] TYPE:  <class 'list'>


In [ ]:
import numpy as np

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print(x + y)
print(np.add(x, y))
print(x.dot(y))
v = np.array([[1,2,3]])
print(v )
print("transpose\n", v.T)

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[19. 22.]
 [43. 50.]]
[[1 2 3]]
transpose
 [[1]
 [2]
 [3]]


1) Create Two numpy array of size 4 X 5 and 5 X 4.

In [ ]:
import numpy as np
arr1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16],[17,18,19,10]]);
arr2 = np.array([[2,4,6,8,10],[12,14,16,18,20],[22,24,26,28,30],[32,34,36,38,40]]);
print(arr1)
print(arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 10]]
[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]]


2) Randomly Initalize that array

In [ ]:
import numpy as np

arr1 = np.random.randint(70, size=(4,5));
arr2 = np.random.randint(50, size=(5,4));

print(arr1)
print(arr2)

[[59 45 29  3 21]
 [25 57  4 21  6]
 [ 8 22 16 24  8]
 [42 18  4  0 37]]
[[26 43 36  7]
 [41 13 25 41]
 [28 14 19 46]
 [49 38 12 38]
 [44  7 16 25]]


3) Perform matrix multiplication

In [ ]:
import numpy as np

arr1 = np.random.randint(9, size=(2,3))
arr2 = np.random.randint(9, size=(3,4))
print(arr1)
print(arr2)

arr = np.dot(arr1, arr2)
print(arr)

[[8 0 8]
 [8 8 6]]
[[5 3 7 6]
 [8 8 0 8]
 [6 3 4 0]]
[[ 88  48  88  48]
 [140 106  80 112]]


4) Perform elementwise matrix multiplication

In [ ]:
import numpy as np

arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[4,8],[0,5]])

arr = np.multiply(arr1, arr2)
print(arr)

[[ 4 16]
 [ 0 20]]


5) Find mean, median of the first matrix.

In [ ]:
import numpy as np

arr = np.random.randint(100, size=(4,5))
print(arr)

# calculates mean along the columns
hmean = np.mean(arr, axis=0)
# calculates mean along the rows
vmean = np.mean(arr, axis=1)
print(hmean, vmean)

# calculates median along the columns
hmed = np.median(arr, axis=0)
# calculates median along the rows
vmed = np.median(arr, axis=1)
print(hmed, vmed)

[[31 21 74 23 95]
 [92 59 16 14 37]
 [92 71 80 98 10]
 [62 84 10 86 89]]
[69.25 58.75 45.   55.25 57.75] [48.8 43.6 70.2 66.2]
[77.  65.  45.  54.5 63. ] [31. 37. 80. 84.]


6) Get the transpose of that Matrix that you created. Create a square matrix and find its deter-
minant.

In [ ]:
import numpy as np

arr = np.random.randint(100, size=(4,5))
print(arr)

arr1 = arr.T
print(arr1)

arr2 = np.transpose(arr)
print(arr2)
print()

mat = np.random.randint(10, size=(3,3))
print(mat)

det1 = np.linalg.det(mat).round()
print(det1)

[[14 85 36 12 94]
 [23  9 89 44 40]
 [98 86 27 11 23]
 [46 41 32 17 61]]
[[14 23 98 46]
 [85  9 86 41]
 [36 89 27 32]
 [12 44 11 17]
 [94 40 23 61]]
[[14 23 98 46]
 [85  9 86 41]
 [36 89 27 32]
 [12 44 11 17]
 [94 40 23 61]]

[[7 0 9]
 [1 8 9]
 [8 5 8]]
-398.0


7) Obtain each row in the second column of the first array.

In [ ]:
import numpy as np

arr = np.random.randint(50, size=(4,5))
print(arr)
# second column will be the second row in the transpose
row = arr.T[1:2]
print(row)

[[59 94 14 73 43]
 [55 21  6 72 81]
 [60 28 42 58 18]
 [37 22  4 16 72]]
[[94 21 28 22]]


8) Convert Numeric entries(columns) of mtcars.csv to Mean Centered Version